spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:things.db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath*:/mapper/**/*.xml

# 文件上传配置
file:
  upload:
    path: /Users/flc/upload
